/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fileJNI */

#ifndef _Included_fileJNI
#define _Included_fileJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fileJNI
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_create
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fileJNI
 * Method:    read
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_read
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fileJNI
 * Method:    forgot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_forgot
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fileJNI
 * Method:    message
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_message
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     fileJNI
 * Method:    search
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_search
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fileJNI
 * Method:    select
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_select
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     fileJNI
 * Method:    display
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_display
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fileJNI
 * Method:    reply
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fileJNI_reply
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
